[package]
name = "voxel_es"
version = "0.1.0"
edition = "2024"


[dependencies]
bevy = { version = "0.18.0", features = ["dynamic_linking", "default", "bevy_winit", "bevy_render", "bevy_pbr"] }
burn = "0.20.0"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
image = "0.24"
zstd = "0.13"
rayon = "1.10"
